# Generated by Django 4.1.7 on 2023-03-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_choise_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choise_img',
        ),
        migrations.AddField(
            model_name='question',
            name='question_img',
            field=models.IntegerField(default=0),
        ),
    ]
